### ISSUE TITLE
thumb设置不可见怎么设置呀

### ISSUE THREAD

**Issue by Adaclass** [warkiz/TickSeekBar#10]

**Comment by warkiz** [comment]
没有提供这个接口，用透明thumb图片？

**Comment by Adaclass** [comment]
大佬，用了透明图片后，
![image](https://user-images.githubusercontent.com/30258067/51361854-4b655380-1b0c-11e9-9414-c95aa3ac352b.png)
UI要做的是这个样子的：
![image](https://user-images.githubusercontent.com/30258067/51361895-73ed4d80-1b0c-11e9-87aa-171fcf63b630.png)
然而我设置黑色的颜色后：
![image](https://user-images.githubusercontent.com/30258067/51362007-d7777b00-1b0c-11e9-9049-dcc834c046be.png)
在手机上有一点点空白。。。

**Comment by Adaclass** [comment]
@warkiz

**Comment by sahil107** [comment]
https://github.com/warkiz
