### ISSUE TITLE
Crash Android 4.3: Error inflating class com.warkiz.tickseekbar.TickSeekBar

### ISSUE THREAD

**Issue by khacdat1994** [warkiz/TickSeekBar#2]
This Log error on Android 4.3:
android.view.InflateException: Binary XML file line #26: Error inflating class com.warkiz.tickseekbar.TickSeekBar
Thanks

**Comment by Ashusolanki** [comment]
i have same issue

**Comment by Diegov17** [comment]
Is this issue resolved? im having it on 4.4.4

**Comment by TheGabCode** [comment]
Will this ever get resolved?

**Comment by guipassos12** [comment]
same issue on kitkat

**Comment by ali-bagheri** [comment]
I too,have same issue. on Api 16.

remove any color attribute from xml layout :(   (can not change default color on below api 21)

**Comment by ali-bagheri** [comment]
Hi,
for resolve:

- remove any color attribute from xml layout
- or use fixed library
https://gofile.io/?c=c56V3d

**Comment by warkiz** [comment]
fixed
