### ISSUE TITLE
When I upload to android studio it gives tons of errors

### ISSUE THREAD

**Issue by MarcVertigo** [warkiz/TickSeekBar#8]
When I download the repo and open with android studio I get tons of errors. Any advice?

![screen shot 2018-09-10 at 2 54 46 pm](https://user-images.githubusercontent.com/39630945/45326743-a1484000-b509-11e8-8053-61f9c3d68e70.png)

**Comment by jpooleycodes** [comment]
Same issue here

**Comment by the-rs** [comment]
Same

**Comment by the-rs** [comment]
@warkiz is the project maintained?

**Comment by the-rs** [comment]
Seems like there's no chance to fix it as long as Google decided to mark certain ColorStateList methods with annotation @UnsupportedAppUsage. See the AOSP sources

**Comment by warkiz** [comment]
fixed
